analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_redundant_argument_values: ignore
    depend_on_referenced_packages: ignore
    document_ignores: ignore
    inference_failure_on_instance_creation: ignore
    lines_longer_than_80_chars: ignore
    strict_raw_type: ignore
    unnecessary_null_comparison: ignore
    use_build_context_synchronously: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false