name: intallek
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.1.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get_it: ^8.0.3
  very_good_analysis: ^8.0.0
  go_router: ^15.1.2
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4
  geocoding: ^4.0.0
  http: ^1.4.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/icons/
    - assets/images/png/ride_type/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/notosans/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/notosans/NotoSansArabic-Medium.ttf
        - asset: assets/fonts/notosans/NotoSansArabic-Bold.ttf

flutter_assets:
  assets_path: assets/
  output_path: lib/core/theme/
  filename: assets.dart
  field_prefix: 
  ignore_comments: true

# flutter gen-l10n